markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html 
excerpt_separator: "<!-- more -->"

github: hedric
author: "hedric"
email: placeholder@mail.com
name: "Hedric's Blog"
baseurl: /
url: hedric.github.io
domain:

all_categories: [
  ["android", "Android","/android/index.html"], 
  ["react", "React Native", "/react/index.html"],
  ["web", "Web","/web/index.html"], 
  ["linux", "Linux","/linux/index.html"],
  ["git", "git","/git/index.html"],
  ["program", "Program","/program/index.html"],
  ["vps", "VPS","/vps/index.html"],
  ["other", "Other","/other/index.html"],
  ["read", "Read","/read/index.html"], 
  ["about", "About","/about.html"]
]

paginate: 10 
paginate_path: "index_:num"

index_layout: "index.html"
category_layout: "_layouts/category.html"
tag_layout: "_layouts/tag.html"

#不使用gems库中的jekyll-paginate-category
#使用基于jekyll-paginate改写的的栏目分页插件，所以jekyll-paginate还需要用上。
#gems: [jekyll-paginate,jekyll-paginate-category]
gems: [jekyll-paginate]

collections:
  docs:
    output: true

copyright: []
#timezone: Asia/Shanghai
